### ISSUE TITLE
Diary CSS

### ISSUE THREAD

**Issue by orienslu** [BuguStudio/blog#1]
每日一个 css 技巧。

**Comment by orienslu** [comment]
### 让 CSS 动画停在最后一帧
```css
animation-fill-mode: forwards;
```

**Comment by orienslu** [comment]
### 设置元素子元素位于 3d 空间
```css
transform-style: preserve-3d;
```

**Comment by orienslu** [comment]
### less @keyframe 变量一种写法
```less
.common-keyframe-mixin(@name, @opacity) {
  @realName: ~"real-@name";  // 名字为组合字符串时可以这样写
  @keyframe @realName {
    to {
      opacity: @opacity;
    }
  }
}
```

**Comment by orienslu** [comment]
### 开启 GPU 加速
CSS 中的以下几个属性能触发硬件加速：
```bash
transform
opacity
filter
will-change
```

用不到以上属性开启加速的方法
```less
transform: translate3d(0, 0, 0);  // 法一
transform: translateZ(0);  // 法二
transform: translateZ(360%); // 法三
```

**Comment by orienslu** [comment]
### iOS  H5 卡顿解决方案
方案一：
```css
// 可删除这一行样式
html, body { height: 100%; }
```

方案二
```css
// 增加这一行，当手指从触摸屏上移开，会保持一段时间的滚动
* { -webkit-overflow-scrolling: touch; }
```
